name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t jvik/elaway-gateway-api:${{ github.event.release.tag_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jvik
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push jvik/elaway-gateway-api:${{ github.event.release.tag_name }}
